# Generated by Django 3.2.7 on 2021-09-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210918_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.domicilio'),
        ),
    ]
